### ISSUE TITLE
Compiled ejb-app does not start

### ISSUE THREAD

**Issue by andrew-k-21-12** [exonum/exonum-java-binding#563]
I've built **ejb-app** using [this](https://github.com/exonum/exonum-java-binding/blob/master/CONTRIBUTING.md#how-to-build) instructions. Even more I tried to rebuild it with `mvn clean install` with no luck.

When I try to launch my **ejb-app**, it throws:
```
dyld: Library not loaded: @rpath/libstd-03b901326ae24853.dylib
  Referenced from: /Users/User/.cargo/bin/ejb-app
  Reason: image not found
[1]    32738 abort      /Users/User/.cargo/bin/ejb-app
```

`otool -l /Users/User/.cargo/bin/ejb-app` showed that the path with required **libstd-03b901326ae24853.dylib** was not included into rpath. I could fix it with:
`install_name_tool -add_rpath /Users/User/.rustup/toolchains/stable-x86_64-apple-darwin/lib/ /Users/User/.cargo/bin/ejb-app`, but after that another error appears:
```
dyld: Symbol not found: __ZN10serde_json2de5POW1017hb458eff36f998f95E
  Referenced from: /Users/User/.cargo/bin/ejb-app
  Expected in: /Users/User/Desktop/exonum/exonum-java-binding/exonum-java-binding-core/rust/target/debug/libjava_bindings.dylib
 in /Users/User/.cargo/bin/ejb-app
[1]    32834 abort      ejb-app
```

Inspecting all available **libjava_bindings.dylib** (`nm -gU /Users/User/Desktop/exonum/exonum-java-binding/exonum-java-binding-core/rust/target/debug/deps/libjava_bindings.dylib.dSYM/Contents/Resources/DWARF/libjava_bindings.dylib`) I could find the one which has required symbol **__ZN10serde_json2de5POW1017hb458eff36f998f95E**, but unfortunately it's impossible to link **ejb-app** with this library (`install_name_tool -add_rpath /Users/User/Desktop/exonum/exonum-java-binding/exonum-java-binding-core/rust/target/debug/deps/libjava_bindings.dylib.dSYM/Contents/Resources/DWARF/ /Users/User/.cargo/bin/ejb-app`):
```
dyld: Library not loaded: @rpath/libjava_bindings.dylib
  Referenced from: /Users/User/.cargo/bin/ejb-app
  Reason: no suitable image found.  Did find:
	/Users/User/Desktop/exonum/exonum-java-binding/exonum-java-binding-core/rust/target/debug/deps/libjava_bindings.dylib.dSYM/Contents/Resources/DWARF/libjava_bindings.dylib: mach-o, but wrong filetype
[1]    33001 abort      ejb-app
```

What am I doing wrong? Any suggestions?

**Comment by skletsun** [comment]
Hi. It looks like you've built the `ejb-app` with toolchain other than 1.26.2. I'd suggest specifying the exact toolchain version in the build command, smth like `cargo +1.26.2 install --debug --force`. And you can check it by executing `./start_cryptocurrency_node.sh` (within the same `exonum-java-binding-core/rust/ejb-app`dir) which prepares all required environment variables and starts cryptocurrency demo based on `ejb-app`.

**Comment by dmitry-timofeev** [comment]
It also seems that `LD_LIBRARY_PATH` must be set to launch the application, the instructions for v0.3 are available here: https://github.com/exonum/exonum-java-binding/blob/v0.3/exonum-java-binding-core/rust/ejb-app/TUTORIAL.md#step-1-configure-environment

**Comment by andrew-k-21-12** [comment]
It works with specific toolchain version provided in the build command, thanks!

**Comment by vitvakatu** [comment]
Great, feel free to ask if you have more questions.
