### ISSUE TITLE
Problem with Lazysodium in gradle

### ISSUE THREAD

**Issue by nadeevkm** [exonum/exonum-java-binding#586]
Greetings!

Today I tried to upgrade to exonum-java-binding-core:0.3 from 0.2 and got next message (while gradle build):

> Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.goterl.lazycode:lazysodium-java:3.3.0.
> Searched in the following locations:
>   - https://repo.maven.apache.org/maven2/com/goterl/lazycode/lazysodium-java/3.3.0/lazysodium-java-3.3.0.pom
>   - https://repo.maven.apache.org/maven2/com/goterl/lazycode/lazysodium-java/3.3.0/lazysodium-java-3.3.0.jar
> Required by:

And here https://mvnrepository.com/artifact/com.goterl.lazycode/lazysodium-java/3.3.0
I saw this note:

> Note: this artifact it located at JCenter repository (http://jcenter.bintray.com/)

So, what is the proper way to fix it?

The whole gradle.build file is

```
group 'ru.iteco.blockchain'

apply plugin: 'java'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile(
            'com.exonum.binding:exonum-java-binding-core:0.3',
            'com.google.code.gson:gson:2.8.5',
            'org.jasypt:jasypt:1.9.2'
    )

}
```

and on 'com.exonum.binding:exonum-java-binding-core:0.2' it works fine...

**Comment by bullet-tooth** [comment]
Hi, @nadeevkm. Thank you for your report.
Lazysodium locates at another repository. 
Updating `repositories` section at your `gradle.build` file should solve the issue:
```
repositories {
    mavenCentral()
    maven {
        url "https://dl.bintray.com/terl/lazysodium-maven"
    }
}
```

**Comment by nadeevkm** [comment]
Updated as your said..

```
group 'ru.iteco.blockchain'

apply plugin: 'java'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
    maven {
        url "https://dl.bintray.com/terl/lazysodium-maven"
    }
}

dependencies {
    compile(
            'com.exonum.binding:exonum-java-binding-core:0.3',
            'com.google.code.gson:gson:2.8.5',
            'org.jasypt:jasypt:1.9.2'
    )

}
```

but unfortunately result is the same.. also tried jCentar() repo with no success..

**Comment by bullet-tooth** [comment]
It's quite weird. I created a test project with your `gradle.build` file and it builds well in my case (even without the bintray repository).
I can suggest you to try to refresh the cached dependencies `./gradlew build --refresh-dependencies`
In case this won't help please send the gradle version, command and terminal output.

**Comment by nadeevkm** [comment]
At last we managed to solve the issue.
The problem was that we had a multimodule-project and keep 
`    repositories {
        mavenCentral()
    }`
in every module's build.gradle. But now we removed all of them and put just one in root build.gradle

`allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}`

and it worked.

Thank you for your assistance!
