### ISSUE TITLE
Where to find PublicKeySerializer at 0.3 version

### ISSUE THREAD

**Issue by nadeevkm** [exonum/exonum-java-binding#608]
Greeting!

I want to migrate my project from exonum-java-binding-core:0.2 to 0.3 and previously I used PublicKeySerializer, like

`
   public ProofMapIndexProxy<PublicKey, User> users() {
        String name = fullIndexName(USERS_STORAGE_NAME);
        return ProofMapIndexProxy.newInstance(name, view, PublicKeySerializer.INSTANCE,
                UserSerializer.INSTANCE);
    }
`

but in 0.3 it seems that you made it package-private

`package com.exonum.binding.common.serialization;

import com.exonum.binding.common.crypto.PublicKey;

enum PublicKeySerializer implements Serializer<PublicKey> {
  INSTANCE;

  @Override
  public byte[] toBytes(PublicKey value) {
    return value.toBytes();
  }

  @Override
  public PublicKey fromBytes(byte[] serializedValue) {
    return PublicKey.fromBytes(serializedValue);
  }

}`

was it on purpose? And should I make my own implementation?

**Comment by bullet-tooth** [comment]
Hi @nadeevkm. At 0.3 we created a helper class for standard serializers.
Please navigate to `com.exonum.binding.common.serialization.StandardSerializers#publicKey`

**Comment by nadeevkm** [comment]
Yep, found it! Thank you!
